### ISSUE TITLE
Data split and GPT2-KG training detail

### ISSUE THREAD

**Issue by zhaone** [nouhadziri/Neural-Path-Hunter#1]
Hi, thanks for your great work!

Recently I want to reproduce your results on the GPT2-KG + NPH setting, but there is no official dataset split provided. Do you plan to public your dataset split later?

And I notice that you did not provide the code of the GPT2-KG model (the one generating responses to be refined),  I wonder if the input of GPT2-KG is just dialog history or dialog history with knowledge triples? Will you provide this piece of code later?

**Comment by ka-furumai** [comment]
Thank you for opening the issue.
I would like to know more details, too.

I have trained small GPT2 model to predict the last utterance by inputting a concatenation of dialogue history and knowledge triples, but it fails to generate a response that reflects the given knowledge.

More information may be needed to reproduce it.
For example, which data was used for training (all conversational data or only knowledge annotated data?), and whether special tokens were added for knowledge triples.

**Comment by nouhadziri** [comment]
@zhaone Thanks for your interest in our work. I wouldn't be able to share the data due to license issues. No official split is provided in the original dataset, and thus we randomly split the dataset in 80/10/10 for the train/valid/test. We do provide how to process the data in Appendix A. 
GPT2-KG is a GPT2 that's fine-tuned on the dialogue history and triples from the KG. Specific control tokens were added at training time such as (sub, pre, obj). We will work on releasing the code soon. 

@ka-furumai as indicated in the Appendix, we filter examples that do not have knowledge triples.

**Comment by zhaone** [comment]
Thanks! Almost the same as my understanding. Close this issue.
